explore_backup backup_dump:
    #!/usr/bin/env bash
    export BACKUP_LOCATION=$(realpath {{ backup_dump }})

    cd backup-explorer

    # Clean up any existing containers and start new ones
    docker compose down

    # Build and start the containers
    docker compose up -d --build

    # Open pgweb in the default web browser
    xdg-open http://localhost:8081

    # Wait for any key press to stop the containers
    read -n 1 -s -r -p "Press any key to stop the backup explorer..."
    echo ""
    echo "Stopping backup explorer..."
    docker compose down
